### ISSUE TITLE
wiki/index/informatika/architektura/oop.md (chyba na Wiki)

### ISSUE THREAD

**Issue by brzzda** [voho/web#10]
V časti "Vzájemné vztahy ojektů" - podčasť "Zobecnění" sa v odstavci pod grafom píše: 

"Potomek může mít i více předků, což někdy vede na tzv. problém diamantu. Proto se ve většině jazyků používá dědičnost jednoduchá (každá třída může mít jen jednoho potomka)."

Nemalo by tam byť "...(každá třída může mít jen jednoho předka)."?

**Comment by voho** [comment]
Je to tak! Opravdu moc děkuju za nahlášení chyby, jdu to hned opravit. Tenhle text jsem psal ještě na škole, už je tedy opravdu starý :).
