### ISSUE TITLE
wiki/index/informatika/algoritmus/asymptoticka-slozitost.md (chyba na Wiki)

### ISSUE THREAD

**Issue by ochaloup** [voho/web#16]
u obrázků je vždý uvedena funkce "Omega", místo omikron a theta. Viz.

* notace Omega omezuje řád růstu náročnosti zdola
* notace Omega omezuje řád růstu náročnosti shora
* notace Omega omezuje řád růstu náročnosti z obou směrů

**Comment by voho** [comment]
máš pravdu, musím to opravit - díky moc za nahlášení!

**Comment by voho** [comment]
opraveno, za chvíli to pushnu, ještě jednou dík

**Comment by ochaloup** [comment]
já dík za článek :smiley:
