### ISSUE TITLE
wiki/index/jazyk/programovani/c.md (chyba na Wiki)

### ISSUE THREAD

**Issue by ino76** [voho/web#18]
http://voho.eu/wiki/c/
"Byl poprvé představen v roce 1972 a jeho autory jsou Brian W. Kernighan a Dennis M. Ritchie."

Brian W. Kernighan neni spoluautorem jazyka C. Je spoluautorem knihy "C Programming Language".

**Comment by voho** [comment]
Díky, opravím!
