### ISSUE TITLE
wiki/index/informatika/oop/navrhovy-vzor/vzor-chovani/state.md (chyba na Wiki)

### ISSUE THREAD

**Issue by svacina** [voho/web#20]
Prosím o zvážení varianty Context objektu bez metod beHappy() a beSad(). Na misto nich umistit jeden setter setState(StateofMind som). Protoze soucasne reseni je proti myslence polymorfismu, musíte mít tolik metod beHappy(), atd. kolik máte přetížených objektů. Tomu jsme se chtěli vyhnout pomocí popisovaného vzoru.

Děkuji za skvělou wikipedii.

Honza

**Comment by voho** [comment]
diky za tip, pokusim se to vylepsit!

**Comment by voho** [comment]
https://github.com/voho/web/commit/8d26931f8e9c4695e2a8a5603888e6533b544baf
