### ISSUE TITLE
wiki/index/matematika/vzorec/kombinatorika.md (chyba na Wiki)

### ISSUE THREAD

**Issue by bornedan** [voho/web#21]
> Základními pojmy kombinatoriky jsou variace (výběr uspořádané k-tice z množiny) a kombinace (výběr podmožiny). **Speciální případ kombinace se nazývá permutace.** Kombinace se od variací liší tím, že nezáleží na pořadí vybraných prvků.
Permutace je speciální případ variace, ne kombinace, jak je uvedeno výše.

**Comment by voho** [comment]
Díky za nahlášení, jdu to hned opravit.
