### ISSUE TITLE
wiki/index/informatika/nastroje/git.md (chyba na Wiki)

### ISSUE THREAD

**Issue by Tovim** [voho/web#22]
Líbí se Vám slovo **zamerguje**? Proč nepoužijete výraz **sloučí**?

Zdravím

**Comment by voho** [comment]
Díky za podnět, slovo nahradím. To původní se mi samozřejmě moc nelíbí, překlad anglických IT termínů byl vždycky problematický. Hlavně u návrhových vzorů je to fuška. Taky zdravím a děkuji :).
